services:
  event-postgres:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - event-server

  db-adminer:
    image: adminer
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      - event-server

  event-redis:
    image: redis
    restart: on-failure
    ports:
      - 6379:6379
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - event-server

volumes:
  postgres_data:

networks:
  event-server:
    name: event-server
    driver: bridge
